#pragma once

#undef  MATRIX_TABLE_START
#undef  MATRIX_ITEM
#undef  MATRIX_TABLE_END

#define MATRIX_TABLE_START      const int matrix_table_status[][HORIZONTAL_MAX] = {

#define MATRIX_ITEM(HORIZONTAL_VERTICAL_0, HORIZONTAL_VERTICAL_1, HORIZONTAL_VERTICAL_2, HORIZONTAL_VERTICAL_3) \
                        { HORIZONTAL_VERTICAL_0, HORIZONTAL_VERTICAL_1,  HORIZONTAL_VERTICAL_2, HORIZONTAL_VERTICAL_3 },

#define MATRIX_TABLE_END        };

#include "Matrix_Table.hpp"